# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: odmrd.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bodmrd.proto\"\x87\x03\n\x04TxCh\x12\x17\n\x04mode\x18\x01 \x01(\x0e\x32\t.TxChMode\x12\x0f\n\x07\x63urr_hz\x18\x02 \x01(\x04\x12\x10\n\x08start_hz\x18\x03 \x01(\x04\x12\x0f\n\x07stop_hz\x18\x04 \x01(\x04\x12\x0f\n\x07step_hz\x18\x05 \x01(\x04\x12\x10\n\x08gain_dbm\x18\x06 \x01(\x02\x12\x16\n\x0epulse_width_us\x18\x07 \x01(\r\x12\x19\n\x11photon_cnt_enable\x18\x08 \x01(\x08\x12\x16\n\x0ephoton_cnt_len\x18\t \x01(\r\x12\x16\n\x0ephoton_cnt_val\x18\n \x03(\x04\x12\x0e\n\x06min_hz\x18\x0b \x01(\x04\x12\x0e\n\x06max_hz\x18\x0c \x01(\x04\x12\x13\n\x0bmin_step_hz\x18\r \x01(\x04\x12\x13\n\x0bmax_step_hz\x18\x0e \x01(\x04\x12\x14\n\x0cmin_gain_dbm\x18\x0f \x01(\x02\x12\x14\n\x0cmax_gain_dbm\x18\x10 \x01(\x02\x12\x1a\n\x12min_pulse_width_us\x18\x11 \x01(\r\x12\x1a\n\x12max_pulse_width_us\x18\x12 \x01(\r\"&\n\x03Msg\x12\n\n\x02rw\x18\x01 \x02(\x08\x12\x13\n\x04txCh\x18\x02 \x01(\x0b\x32\x05.TxCh*-\n\x08TxChMode\x12\x0b\n\x07\x44ISABLE\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x08\n\x04SCAN\x10\x02')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'odmrd_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TXCHMODE._serialized_start=449
  _TXCHMODE._serialized_end=494
  _TXCH._serialized_start=16
  _TXCH._serialized_end=407
  _MSG._serialized_start=409
  _MSG._serialized_end=447
# @@protoc_insertion_point(module_scope)
